### ISSUE TITLE
Migrations always include `Alter field format_type on film`

### ISSUE THREAD

**Issue by p-j-smith** [UCL-ARC/museum_of_dreams#112]
### Definition of Done / Acceptance Criteria

Running `python manage.py makemigrations` doesn't (unnecessarily) include alterations to the format type of the `Film` model 

### Testing

Without making any changes to the code, run `python manage.py makemigrations` and check the `Film` model is not altered

### Comments

I think the format type always changes because `FORMAT_CHOICES` is a set:
https://github.com/UCL-ARC/museum_of_dreams/blob/90db50e9bd558b0953f76a421667512cb35c3120/mod_app/models/film_model.py#L72-L84
This means the order of the tuples is not guaranteed. Changing `FORMAT_CHOICES` to a list should resolve the issue

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK
